[package]
name = "httpine"
version = "0.1.0"
edition = "2021"
authors = ["Mike Sheb <sheb.gregor@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
